# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cjgbkqvM-CQv6A3Jkl-W8dhpZQ-Y_Au
"""

!pip install ydata-profiling

# importig liberaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


from pandas_profiling import ProfileReport

"""# **Get Data**"""

df = pd.read_csv("/content/train.csv")

"""# **Explore Data**"""

df.head()

print(f"Dataset contains {df.shape[0]} Rows and {df.shape[1]} columns")

df.info()

# describe
df.describe()

report = ProfileReport(df)
report

"""# **Data Cleaning**"""

df.nunique()

df.isna().sum()

"""Drop columns with high missing values"""

df.drop("Cabin",axis=1,inplace=True)

"""Fix columns with little missing values"""

df['Embarked'].fillna('S',inplace=True)
df['Age'].fillna(df['Age'].mean(),inplace=True)

df.isna().sum()

df.dtypes

"""Check Duplication"""

df.duplicated().sum()

"""*Converting data types*"""

# Convert data types if needed
df['Survived'] = df['Survived'].astype('category')
df['Pclass'] = df['Pclass'].astype('category')
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

df.dtypes

"""# **Summary of Cleaning Steps :**



1.   **Remove missing values in Cabin , Filled missing values in ( Age , Embarked ) columns.**
2.   **Remove Dublicates Rows.**
3.   **Converted Data Types.**

# **Data Visualization**

# Overall survival rate
"""

sns.countplot(x='Survived', data=df)
plt.title('Survival Distribution (0 = Died, 1 = Survived)', fontsize=16)
plt.show()

"""# Female vs Male"""

fig = px.pie(df, names='Sex', title='Female vs Male')
fig.show()

"""# Survival by gender

"""

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title('Survival by Gender', fontsize=16)
plt.legend(title='Survived', loc='upper right', labels=['Died', 'Survived'])
plt.show()

"""# Survival by passenger class

"""

sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title('Survival by Passenger Class', fontsize=12)
plt.legend(title='Survived', loc='upper left', labels=['Died', 'Survived'])
plt.show()

"""# Age distribution

"""

sns.histplot(data=df, x='Age', hue='Survived', multiple='stack', kde=True)
plt.title('Age Distribution by Survival', fontsize=16)
plt.show()

"""# Fare distribution

"""

sns.histplot(data=df, x='Fare', hue='Survived', multiple='stack', kde=True)
plt.title('Fare Distribution by Survival', fontsize=16)
plt.xlim(0, 100)  # Zoom on most common fares
plt.show()

"""## Bonus: Survival rate by class and gender

"""

sns.barplot(x='Pclass', y='Survived', hue='Sex', data=df, ci=None)
plt.title('Survival Rate by Class and Gender', fontsize=16)
plt.ylabel('Survival Rate')
plt.show()